Refactored code base to add remove functionality and improved code usability

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,27 +2,61 @@
 
 # Sets up bash profile, vimrc and more. Always WIP.
 set -e
+echo "Starting Setup" && sleep 2
+# if there's a bashrc already and it isn't a link, check the following.
+if [ -f $HOME/.bashrc ] && [ ! -L $HOME/.bashrc ]; then
+  # add the sourcing line to default .bashrc if not there already
+  case `grep -Fx "test -d $HOME/.bashrc && . $HOME/.bashrc.personal" "$HOME/.bashrc" >/dev/null; echo $?` in
+    0)
+      echo "bashrc already exists and is setup already"
+      ;;
+    1)
+      echo "test -d $HOME/.bashrc && . $HOME/.bashrc.personal" >> $HOME/.bashrc
+      # code if not found
+      ;;
+    *)
+      echo "Unknown error, chec if grep is installed."
+      # code if an error occurred
+      ;;
+  esac
+    ln -sf "$PWD/.bashrc.personal" "$HOME/.bashrc.personal"
+else
+  # if no bashrc exists right now, force-link default bashrc to be default
+  # bashrc
+  if [ ! -f $HOME/.bashrc ]; then
+    ln -sf "$PWD/.bashrc.default" "$HOME/.bashrc"
+  fi
+fi
 
-# copy bashrc and bash aliases in.
-# if there's existing .profile and it isn't a symlink, then move it to a backup
 if [ -f $HOME/.profile ] && [ ! -L $HOME/.profile ]; then
-  mv -f $HOME/.profile $HOME/.profile.bak
+  # add the sourcing line to default .profile if not there already
+  case `grep -Fx "test -d $HOME/.profile && . $HOME/.profile.personal"  "$HOME/.profile" >/dev/null; echo $?` in
+    0)
+      echo "profile already exists and is setup already"
+      ;;
+    1)
+      echo "test -d $HOME/.profile && . $HOME/.profile.personal" >> $HOME/.profile
+      # code if not found
+      ;;
+    *)
+      echo "Unknown error, chec if grep is installed."
+      # code if an error occurred
+      ;;
+  esac
+    ln -sf "$PWD/.profile.personal" "$HOME/.profile.personal"
+else
+  # if no profile exists right now, force-link default profile to be default
+  # profile
+  if [ ! -f $HOME/.profile ]; then
+    ln -sf "$PWD/.profile.default" "$HOME/.profile"
+  fi
 fi
-
-if [ -f $HOME/.bashrc ] &&  [ ! -L $HOME/.bashrc ]; then
-  mv -f $HOME/.bashrc $HOME/.bashrc.bak
-fi
-if ! command -v which &> /dev/null; then
-  echo "Looks like which is not installed, install whicn bfore
-  proceeding further."
-  exit 1
-fi
-ln -sf "$PWD/.profile" "$HOME/.profile"
-ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
+# Doesn't seem like there's typically a default .bash_aliases, so won't
+# go through the same sharade. Same for .gitconfig. 
+ln -sf "$PWD/.bash_aliases.personal" "$HOME/.bash_aliases"
 ln -sf "$PWD/.gitconfig" "$HOME/.gitconfig"
 
 for i in vim tmux; do
   cd $i && ./setup
   cd -
-  sleep 3
 done
