Modified documentation, setup files and more

diff --git a/vim/setup b/vim/setup
--- a/vim/setup
+++ b/vim/setup
@@ -1,7 +1,25 @@
 #!/bin/bash
-if [ -z "$(which vim)" -o -z "$(which vimtutor)" ]; then
-  echo "Doesn't look like you have full vim version, skipping."
-else
+echo "Initializing Vim setup"
+sleep 1
+if ! command -v vim &>/dev/null && ! command -v vimtutor &>/dev/null; then
+  echo "Doesn't look like you have full vim version, skipping..."
+elif [ @ -f $HOME/.vimrc ]; then
   ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
   echo "Enter and quit vim twice, then type reset on Bash shell to setup vim properly"
+  echo "Keys to press: vim <Enter> <Enter> :q vim :q reset"
+  echo "Vim setup complete, quitting"
+elif [ -f $HOME/.vimrc ] && [ ! -L $HOME/.vimrc ]; then
+  echo "It seems that .vimrc is in place already."
+  echo "Do you want to preserve yours and try mine?[yes|no]"
+  read $response
+  if $response == "yes"; then
+    mv  $HOME/.vimrc $HOME/.vimrc.bak
+    echo "Your .vimrc have been backed up in .vimrc.bak"
+  elif $response == "no"; then
+    echo "Vim setup skipped, quitting"
+  else
+    echo "Invalid response, quitting"
+  fi
+  unset $response
 fi
+
